const inventory = [
{id:'M-BL-001',name:'Navy Structured Blazer',category:'Blazers',collection:'Menswear',color:'Navy',style:['Classic','Minimal'],occasions:['Job Interview','Networking Event','Corporate Event'],sizes:['S','M','L','XL'],price:220000,desc:'Crisp wool-blend tailoring with a confident shoulder.',image:'blazer-navy.svg'},
{id:'M-BL-002',name:'Charcoal Relaxed Blazer',category:'Blazers',collection:'Menswear',color:'Grey',style:['Modern','Soft'],occasions:['Job Interview','Networking Event','Corporate Event'],sizes:['S','M','L'],price:210000,desc:'A softer tailored layer for flexible professional dressing.',image:'blazer-charcoal.svg'},
{id:'M-BL-003',name:'Black Single-Breasted Blazer',category:'Blazers',collection:'Menswear',color:'Black',style:['Classic','Minimal'],occasions:['Job Interview','Formal Dinner','Wedding'],sizes:['S','M','L','XL'],price:230000,desc:'A dependable black blazer with clean, minimal lines.',image:'blazer-black.svg'},
{id:'M-SH-001',name:'White Oxford Shirt',category:'Shirts & Blouses',collection:'Menswear',color:'White',style:['Classic','Minimal'],occasions:['Job Interview','Networking Event','Corporate Event','Graduation'],sizes:['S','M','L','XL'],price:120000,desc:'A sharp cotton Oxford that anchors a formal look.',image:'shirt-white.svg'},
{id:'M-SH-002',name:'Light Blue Poplin Shirt',category:'Shirts & Blouses',collection:'Menswear',color:'Blue',style:['Modern','Soft'],occasions:['Job Interview','Networking Event','Corporate Event'],sizes:['S','M','L'],price:120000,desc:'Soft blue poplin for polished but easy dressing.',image:'shirt-blue.svg'},
{id:'M-SH-003',name:'Cream Fine-Knit Polo',category:'Shirts & Blouses',collection:'Menswear',color:'Cream',style:['Minimal','Soft'],occasions:['Networking Event','Formal Dinner','Wedding'],sizes:['S','M','L','XL'],price:140000,desc:'A refined knit layer with an easy collar.',image:'shirt-cream.svg'},
{id:'M-TR-001',name:'Black Tailored Trousers',category:'Trousers',collection:'Menswear',color:'Black',style:['Classic','Minimal'],occasions:['Job Interview','Corporate Event','Graduation'],sizes:['S','M','L','XL'],price:160000,desc:'Straight tailored trousers with a versatile finish.',image:'trousers-black.svg'},
{id:'M-SH-004',name:'Black Derby Shoes',category:'Shoes',collection:'Menswear',color:'Black',style:['Classic','Modern'],occasions:['Job Interview','Corporate Event','Wedding'],sizes:['S','M','L'],price:180000,desc:'Polished leather Derbies for a clean finish.',image:'shoes-black.svg'},
{id:'M-SH-005',name:'Black Leather Loafers',category:'Shoes',collection:'Menswear',color:'Black',style:['Classic','Minimal'],occasions:['Job Interview','Networking Event','Formal Dinner'],sizes:['S','M','L','XL'],price:180000,desc:'Classic leather loafers, easy and formal.',image:'shoes-black.svg'},
{id:'M-AC-001',name:'Navy Silk Tie',category:'Accessories',collection:'Menswear',color:'Navy',style:['Classic'],occasions:['Job Interview','Wedding','Corporate Event'],sizes:['One Size'],price:70000,desc:'A muted silk tie for occasions that call for one.',image:'accessory-navy.svg'},
{id:'M-AC-002',name:'Black Leather Belt',category:'Accessories',collection:'Menswear',color:'Black',style:['Classic','Minimal'],occasions:['Job Interview','Networking Event','Corporate Event'],sizes:['S','M','L'],price:60000,desc:'A simple finishing detail in smooth leather.',image:'accessory-black.svg'},
{id:'W-BL-001',name:'Grey Tailored Blazer',category:'Blazers',collection:'Womenswear',color:'Grey',style:['Classic','Modern'],occasions:['Job Interview','Networking Event','Corporate Event'],sizes:['XS','S','M','L'],price:230000,desc:'Structured grey tailoring with a versatile silhouette.',image:'blazer-grey.svg'},
{id:'W-BL-002',name:'Black Tailored Blazer',category:'Blazers',collection:'Womenswear',color:'Black',style:['Classic','Minimal'],occasions:['Job Interview','Corporate Event','Formal Dinner'],sizes:['XS','S','M','L','XL'],price:240000,desc:'A tailored black blazer designed for repeat wear.',image:'blazer-black.svg'},
{id:'W-BL-003',name:'Cream Relaxed Blazer',category:'Blazers',collection:'Womenswear',color:'Cream',style:['Soft','Modern'],occasions:['Networking Event','Wedding','Graduation'],sizes:['XS','S','M','L'],price:220000,desc:'Relaxed cream tailoring for soft occasion layers.',image:'blazer-cream.svg'},
{id:'W-SH-001',name:'White Satin Blouse',category:'Shirts & Blouses',collection:'Womenswear',color:'White',style:['Classic','Soft'],occasions:['Job Interview','Networking Event','Corporate Event'],sizes:['XS','S','M','L'],price:130000,desc:'A fluid satin blouse with a subtle sheen.',image:'blouse-white.svg'},
{id:'W-SH-002',name:'Cream Fine-Knit Top',category:'Shirts & Blouses',collection:'Womenswear',color:'Cream',style:['Minimal','Soft'],occasions:['Job Interview','Networking Event','Graduation'],sizes:['XS','S','M','L','XL'],price:130000,desc:'A soft fine-knit top that keeps the palette considered.',image:'shirt-cream.svg'},
{id:'W-TR-001',name:'Wide-Leg Black Trousers',category:'Trousers',collection:'Womenswear',color:'Black',style:['Modern','Minimal'],occasions:['Networking Event','Corporate Event','Graduation'],sizes:['XS','S','M','L'],price:170000,desc:'Fluid wide-leg tailoring with a comfortable finish.',image:'trousers-black.svg'},
{id:'W-SK-001',name:'Black Midi Skirt',category:'Skirts',collection:'Womenswear',color:'Black',style:['Classic','Minimal'],occasions:['Networking Event','Corporate Event','Graduation'],sizes:['XS','S','M','L'],price:150000,desc:'A versatile midi skirt with a clean line.',image:'skirt-black.svg'},
{id:'W-DR-001',name:'Black Midi Dress',category:'Dresses',collection:'Womenswear',color:'Black',style:['Minimal','Classic'],occasions:['Wedding','Formal Dinner','Corporate Event'],sizes:['XS','S','M','L'],price:270000,desc:'A refined black midi dress to build around.',image:'dress-black.svg'},
{id:'W-DR-002',name:'Navy Column Dress',category:'Dresses',collection:'Womenswear',color:'Navy',style:['Classic','Statement'],occasions:['Wedding','Graduation','Formal Dinner'],sizes:['XS','S','M','L'],price:300000,desc:'A clean navy column shape for memorable occasions.',image:'dress-navy.svg'},
{id:'W-SH-003',name:'Black Low-Heel Pumps',category:'Shoes',collection:'Womenswear',color:'Black',style:['Classic','Minimal'],occasions:['Job Interview','Corporate Event','Wedding'],sizes:['XS','S','M','L'],price:180000,desc:'Comfort-conscious pumps with a low heel.',image:'shoes-black.svg'},
{id:'W-SH-004',name:'Black Loafers',category:'Shoes',collection:'Womenswear',color:'Black',style:['Minimal','Modern'],occasions:['Job Interview','Networking Event','Graduation'],sizes:['XS','S','M','L','XL'],price:170000,desc:'Understated loafers for long professional days.',image:'shoes-black.svg'},
{id:'W-AC-001',name:'Structured Black Bag',category:'Accessories',collection:'Womenswear',color:'Black',style:['Classic','Minimal'],occasions:['Job Interview','Corporate Event','Formal Dinner'],sizes:['One Size'],price:100000,desc:'A structured bag that keeps the outfit composed.',image:'bag-neutral.svg'},
{id:'W-AC-002',name:'Neutral Shoulder Bag',category:'Accessories',collection:'Womenswear',color:'Beige',style:['Soft','Modern'],occasions:['Wedding','Graduation','Networking Event'],sizes:['One Size'],price:100000,desc:'A neutral shoulder bag with an occasion-ready shape.',image:'bag-neutral.svg'}
];
const occasionContent=[['Job Interview','Structured, polished, understated.'],['Networking Event','Professional without looking overdressed.'],['Corporate Event','Refined pieces that move beyond the office.'],['Wedding','Occasion-ready without unnecessary ownership.'],['Graduation','Photogenic, comfortable, reusable combinations.']];
const faqs=[['Is FORME a real rental service?','This is a frontend MVP prototype for demonstrating the customer journey. Booking, inventory and delivery are simulated.'],['Does FORME identify my clothing from an image?','Not in this prototype. You upload a photo then confirm the item type and colour, so the rule-based styling logic has the right starting point.'],['How long is a rental?','Prototype prices are displayed for a three-day rental. Your suggested delivery window is two days before your event through one day after.'],['What if an item does not fit?','A production version would include detailed garment measurements and support. This prototype includes a simple size guide only.']];
