/* Deterministic, role-first FORME outfit planner. Owned wardrobe items never need inventory IDs. */
const PRIMARY_ROLES=new Set(['TOP','BOTTOM','OUTERWEAR','ONE_PIECE','SHOES','BAG']);
const ROLE_PATTERNS={BAG:['bag','handbag','shoulder bag','tote','clutch'],SHOES:['shoe','loafer','derby','pump','heel','flat','sneaker'],ONE_PIECE:['dress','jumpsuit'],OUTERWEAR:['blazer','jacket','coat','suit jacket'],TOP:['shirt','blouse','t shirt','tshirt','polo','knit','knitwear','sweater','top'],BOTTOM:['trouser','pant','skirt','short'],ACCESSORY:['tie','belt','scarf','jewellery','jewelry','watch','accessory','accessories']};
const COLOUR_MATCHES={Black:['White','Cream','Grey','Navy','Blue','Beige','Brown'],Navy:['White','Cream','Grey','Blue','Brown','Beige'],Grey:['White','Black','Navy','Cream','Blue'],Beige:['White','Black','Brown','Cream','Navy'],Brown:['White','Cream','Navy','Beige','Blue'],Blue:['White','Navy','Grey','Cream','Beige'],Cream:['Black','Navy','Grey','Brown','Blue','Beige'],White:['Black','Navy','Grey','Beige','Brown','Blue','Cream'],Green:['White','Cream','Black','Navy'],Red:['Black','White','Navy','Cream']};
const STYLE_DIRECTIONS={Classic:['Classic','Modern','Minimal'],Modern:['Modern','Classic','Minimal'],Minimal:['Minimal','Classic','Modern'],Soft:['Soft','Modern','Classic'],Statement:['Statement','Modern','Classic']};
const LOOK_NAMES=['BEST MATCH','ALTERNATIVE EDIT','ANOTHER DIRECTION'];

function normaliseLabel(value=''){return String(value).toLowerCase().replace(/&/g,' and ').replace(/[-_/]/g,' ').replace(/\s+/g,' ').trim();}
function resolveRole(rawCategory='',name=''){const label=`${normaliseLabel(name)} ${normaliseLabel(rawCategory)}`;for(const [role,patterns] of Object.entries(ROLE_PATTERNS)){if(patterns.some(pattern=>label.includes(pattern)))return role;}return'OTHER';}
function normalizeGarment(item={},source='owned'){if(typeof item==='string')item={type:item};const rawCategory=item.type||item.category||item.subtype||item.itemType||'';const name=item.name||item.itemName||'';return{id:item.id||'',name,rawCategory,role:resolveRole(rawCategory,name),subtype:getAccessorySubtype(rawCategory,name),color:item.color||'',collection:item.collection||'',image:item.image||item.file||'',source};}
function getOutfitRole(value='',name=''){return typeof value==='object'?normalizeGarment(value).role:resolveRole(value,name);}
function getProductRole(product){return normalizeGarment(product,'inventory').role;}
function getAccessorySubtype(value='',name=''){const label=`${normaliseLabel(name)} ${normaliseLabel(value)}`;return['tie','belt','scarf','jewellery','jewelry','watch'].find(type=>label.includes(type))||'accessory';}
function ownedFromState(state){if(state.ownedItem)return normalizeGarment(state.ownedItem,state.source||'wardrobe');return normalizeGarment({id:state.ownedId||state.wardrobeId||'',name:state.itemName||'',type:state.itemType||state.type||'',category:state.category||'',subtype:state.subtype||'',color:state.color||'',image:state.file||''},state.source||'owned');}
function getMissingRoles(ownedRole){switch(ownedRole){case'OUTERWEAR':return['TOP','BOTTOM','SHOES'];case'TOP':return['OUTERWEAR','BOTTOM','SHOES'];case'BOTTOM':return['TOP','OUTERWEAR','SHOES'];case'ONE_PIECE':return['OUTERWEAR','SHOES','BAG'];case'SHOES':return['TOP','BOTTOM','OUTERWEAR'];case'BAG':return['TOP','BOTTOM','OUTERWEAR'];case'ACCESSORY':return['TOP','BOTTOM','OUTERWEAR','SHOES'];default:return['TOP','BOTTOM','OUTERWEAR','SHOES'];}}
function colourScore(ownedColor,candidateColor){if(!ownedColor||ownedColor==='Other'||!candidateColor)return 0;if(ownedColor===candidateColor)return 1;return(COLOUR_MATCHES[ownedColor]||[]).includes(candidateColor)?3:0;}
function scoreProduct(product,state,targetStyle,targetCollection){let score=4;if(product.occasions?.includes(state.occasion))score+=5;if(product.style?.includes(targetStyle))score+=3;score+=colourScore(state.color,product.color);if(product.collection===targetCollection)score+=2;if(product.style?.length>1)score++;return score;}
function collectionTargets(state){if(state.collection==='Both')return['Menswear','Womenswear','Menswear'];const selected=state.collection||'Menswear';return[selected,selected,selected];}
function eligibleForRole(product,role,owned,targetCollection){if(!product||product.availability===false||getProductRole(product)!==role||product.collection!==targetCollection)return false;if(owned.role!=='ACCESSORY'&&getProductRole(product)===owned.role)return false;if(role==='ACCESSORY'&&owned.role==='ACCESSORY'&&getAccessorySubtype(product.category,product.name)===owned.subtype)return false;return true;}
function candidateLevels(role,state,targetStyle,targetCollection,owned){const base=inventory.filter(product=>eligibleForRole(product,role,owned,targetCollection));const colourMatch=product=>colourScore(owned.color,product.color)>0;const occasionMatch=product=>product.occasions?.includes(state.occasion);const styleMatch=product=>product.style?.includes(targetStyle);return[base.filter(product=>occasionMatch(product)&&styleMatch(product)&&colourMatch(product)),base.filter(product=>occasionMatch(product)&&colourMatch(product)),base.filter(occasionMatch),base];}
function rankedForRole(role,state,targetStyle,targetCollection,owned){const level=candidateLevels(role,state,targetStyle,targetCollection,owned).find(items=>items.length)||[];return level.sort((a,b)=>{const difference=scoreProduct(b,state,targetStyle,targetCollection)-scoreProduct(a,state,targetStyle,targetCollection);return difference||b.id.localeCompare(a.id);});}
function validateLook(items,state,targetCollection,owned=ownedFromState(state)){const ids=new Set(),roles=new Set();for(const item of items){if(!item||!inventory.some(product=>product.id===item.id)||item.availability===false||ids.has(item.id))return false;ids.add(item.id);const role=getProductRole(item);if(owned.role!=='ACCESSORY'&&role===owned.role)return false;if(PRIMARY_ROLES.has(role)&&roles.has(role))return false;roles.add(role);if(item.collection!==targetCollection)return false;if(owned.role==='ACCESSORY'&&role==='ACCESSORY'&&getAccessorySubtype(item.category,item.name)===owned.subtype)return false;}return items.length>0;}
function buildLook(state,targetStyle,targetCollection,variation){const owned=ownedFromState(state),items=[];for(const role of getMissingRoles(owned.role)){const ranked=rankedForRole(role,state,targetStyle,targetCollection,owned);if(!ranked.length)continue;const product=ranked[Math.min(variation,ranked.length-1)];if(product&&!items.some(item=>item.id===product.id))items.push(product);}
  if(owned.role==='ONE_PIECE'&&!items.some(item=>getProductRole(item)==='BAG')){const accessory=rankedForRole('ACCESSORY',state,targetStyle,targetCollection,owned)[variation];if(accessory&&!items.some(item=>item.id===accessory.id))items.push(accessory);}
  return validateLook(items,state,targetCollection,owned)?items:[];
}
function explainLook(state,items){const roles=items.map(getProductRole);if(roles.includes('OUTERWEAR'))return`Structured layers complete your ${String(state.color).toLowerCase()} ${String(state.itemType).toLowerCase()} without replacing it.`;if(roles.includes('SHOES'))return`Focused finishing pieces keep the look right for ${String(state.occasion).toLowerCase()}.`;return'Only the missing pieces are included.';}
function recommendationSets(state){const targets=collectionTargets(state),directions=STYLE_DIRECTIONS[state.style]||['Classic','Modern','Minimal'],looks=[];for(let index=0;index<3;index++){let items=[];for(let variation=0;variation<4;variation++){const candidate=buildLook(state,directions[index],targets[index],variation);if(!candidate.length)continue;const signature=candidate.map(item=>item.id).join('|');const duplicate=looks.some(look=>look.items.map(item=>item.id).join('|')===signature);if(!duplicate){items=candidate;break;}}if(items.length)looks.push({id:`look-${index+1}`,title:LOOK_NAMES[index],items,explanation:explainLook(state,items),collection:targets[index]});}return looks;}
